### ISSUE TITLE
Add head of HR email to recruitment page

### ISSUE THREAD

**Issue by AugustPaulsrud** [armada-ths/armada.nu#16]
![Image](https://github.com/armada-ths/armada.nu/assets/61270520/a8269517-6307-416a-ac14-c7d188b39f02)

Add a link to the email of the head of HR, if one is added to the AIS.

**Comment by AugustPaulsrud** [comment]
how to fetch emails are shown in the about/team page. Must handle no email being added

**Comment by Duosi-Dai** [comment]
Hi, 
How can I get the API key for the email of HR?

I got this, but didnt see the email address key:

  {
    "id": 9,
    "role": "Project Group – Head of HR",
    "people": [
      {
        "id": 10413,
        "name": " ",
        "picture": " ",
        "linkedin_url": "https://www.linkedin.com/in/goutam-baid/",
        "programme": "Production Engineering and Management (M.Sc)",
        "role": "Project Group – Head of HR"
      }
    ]
  },
